version: '3'
services:
  postgres:
    container_name: hackerqueue-pg
    image: postgres:9.6.3
    environment:
      POSTGRES_PASSWORD: hackerx
      POSTGRES_USER: hacker
      POSTGRES_DB: hackerqueue
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
  web:
    build: .
    image: ledgehog:latest
    environment:
      DB_HOST: postgres
      DATABASE_URL: "postgres://hacker:hackerx@postgres:5432/hackerqueue"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres:postgres